debug: false # 스프링 부트의 debug 로그를 안보려고 false로 설정
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # 쿼리문에서 ?로 표시되는 부분 보여줌

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: dongmin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated # API 로 만들어줄 레포지토리를 찾는 전략 -> @Repository 가 붙은 것만 감지한다.
  thymeleaf3.decoupled-logic: true

# yml 파일은 ---로 도큐먼트를 구분한다. 새로운 도큐먼트 시작!
---
spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL} # 여기 username, password 가 포함되어 있음!
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always